# Run: conda env create -f environment.yml
name: multireg
channels:
  - conda-forge
  - defaults
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip=24.0
  - nvidia/label/cuda-12.8.0::cuda-toolkit
  - nvidia/label/cuda-12.8.0::cuda-cudart
  - pip:
      # Currently using 2.8.0+cu12.8
      - torch==2.8.0
      - torchvision==0.23.0
      - opencv-python==4.12.0.88
      - numpy==2.2.6
      - numpy-quaternion==2024.0.12
      - scipy==1.15.3
      - tqdm==4.67.1
      - coloredlogs==15.0.1
      - easydict==1.13
      - nibabel==5.3.2
      - scikit-learn==1.7.2
      - einops==0.8.1
      - ipdb==0.13.13
      - tensorboard==2.20.0
      - tensorboardX==2.6.4
      - scikit-image==0.25.2
      - matplotlib==3.10.7
      - addict==2.4.0
      - plyfile==1.1.3
      - pandas==2.3.3
      - open3d==0.19.0
      - pytools==2025.2.5
      - ruamel.yaml==0.18.16
      - torch_scatter==2.1.2
      - pin==3.8.0